apistrings_read={ #Index of Nice Name:Telemachus API String
"pause_state":"p.paused",

"throttle_status":"f.throttle",
"rcs_status":"v.rcsValue",
"sas_status":"v.sasValue",
"action_group_light":"v.lightValue",
"action_group_gear":"v.gearValue",
"action_group_brake":"v.brakeValue",

"universal_time":"t.universalTime",

"target_name":"tar.name",
"target_type":"tar.type",
"target_distance":"tar.distance",
"target_relative_velocity":"tar.o.relativeVelocity",
"target_velocity":"tar.o.velocity",
"target_periapsis":"tar.o.PeA",
"target_apoapsis":"tar.o.ApA",
"target_time_to_apoapsis":"tar.o.timeToAp",
"target_time_to_periapsis":"tar.o.timeToPe",
"target_inclination":"tar.o.inclination",
"target_eccentricity":"tar.o.eccentricity",
"target_period":"tar.o.period",
"target_argument_of_periapsis":"tar.o.argumentOfPeriapsis",
"target_transition_1":"tar.o.timeToTransition1",
"target_transition_2":"tar.o.timeToTransition2",
"target_semimajor_axis":"tar.o.sma",
"target_longitude_ascending_node":"tar.o.lan",
"target_mean_anomaly":"tar.o.maae",
"target_time_of_periapsis_passage":"tar.o.timeOfPeriapsisPassage",
"target_true_anomaly":"tar.o.trueAnomaly",
"target_orbiting_body":"tar.o.orbitingBody",

"vessel_velocity":"o.velocity",
"vessel_periapsis":"o.PeA",
"vessel_apoapsis":"o.ApA",
"vessel_time_to_apoapsis":"o.timeToAp",
"vessel_time_to_periapsis":"o.timeToPe",
"vessel_inclination":"o.inclination",
"vessel_eccentricity":"o.eccentricity",
"vessel_period":"o.period",
"vessel_argument_of_periapsis":"o.argumentOfPeriapsis",
"vessel_transition_1":"o.timeToTransition1",
"vessel_transition_2":"o.timeToTransition2",
"vessel_semimajor_axis":"o.sma",
"vessel_longitude_ascending_node":"o.lan",
"vessel_mean_anomaly":"o.maae",
"vessel_time_of_periapsis_passage":"o.timeOfPeriapsisPassage",
"vessel_true_anomaly":"o.trueAnomaly",
"vessel_orbiting_body":"o.orbitingBody",

"temperature_sensor":"s.sensor.temp",
"pressure_sensor":"s.sensor.pres",
"gravity_sensor":"s.sensor.grav",
"acceleration_sensor":"s.sensor.acc",

"vessel_altitude":"v.altitude",
"vessel_asl_height":"v.heightFromTerrain",
"vessel_mission_time":"v.missionTime",
"vessel_surface_velocity":"v.surfaceVelocity",
"vessel_surface_velocity_x":"v.surfaceVelocityx",
"vessel_surface_velocity_y":"v.surfaceVelocityy",
"vessel_surface_velocity_z":"v.surfaceVelocityz",
"vessel_angular_velocity":"v.angularVelocity",
"vessel_orbital_velocity":"v.orbitalVelocity",
"vessel_surface_speed":"v.surfaceSpeed",
"vessel_vertical_speed":"v.verticalSpeed",
"vessel_gee_force":"v.geeForce",
"vessel_atmospheric_density":"v.atmosphericDensity",
"vessel_longitude":"v.long",
"vessel_latitude":"v.lat",
"vessel_dynamic_pressure":"v.dynamicPressure",
"vessel_name":"v.name",
"vessel_angle_to_prograde":"v.angleToPrograde",
"vessel_body":"v.body",
"vessel_heading":"n.heading",
"vessel_pitch":"n.pitch",
"vessel_roll":"n.roll",
"vessel_heading_raw":"n.rawheading",
"vessel_pitch_raw":"n.rawpitch",
"vessel_roll_raw":"n.rawroll",

"docking_delta_x_angle":"dock.ax",
"docking_delta_y_angle":"dock.ay",
"docking_delta_z_angle":"dock.az",
"docking_delta_x":"dock.x",
"docking_delta_y":"dock.y",
"docking_delta_z":"dock.z",

"resource_lf_max":"r.resourceMax[LiquidFuel]",
"resource_ec_max":"r.resourceMax[ElectricCharge]",
"resource_ox_max":"r.resourceMax[Oxidizer]",
"resource_ia_max":"r.resourceMax[IntakeAir]",
"resource_sf_max":"r.resourceMax[SolidFuel]",
"resource_mp_max":"r.resourceMax[MonoPropellant]",
"resource_xg_max":"r.resourceMax[XenonGas]",

"resource_lf_current":"r.resource[LiquidFuel]",
"resource_ec_current":"r.resource[ElectricCharge]",
"resource_ox_current":"r.resource[Oxidizer]",
"resource_ia_current":"r.resource[IntakeAir]",
"resource_sf_current":"r.resource[SolidFuel]",
"resource_mp_current":"r.resource[MonoPropellant]",
"resource_xg_current":"r.resource[XenonGas]",
"api_version":"a.version"
}

apistrings_write={ #Map of human name:Telemachus API string for functions
"action_group_1":"f.ag1",
"action_group_2":"f.ag2",
"action_group_3":"f.ag3",
"action_group_4":"f.ag4",
"action_group_5":"f.ag5",
"action_group_6":"f.ag6",
"action_group_7":"f.ag7",
"action_group_8":"f.ag8",
"action_group_9":"f.ag9",
"action_group_10":"f.ag10",

"abort":"f.abort",
"stage":"f.stage",

"throttle_zero":"f.throttleZero",
"throttle_full":"f.throttleFull",
"throttle_up":"f.throttleUp",
"throttle_down":"f.throttleDown",
"set_throttle":"f.setThrottle",

"set_timewarp":"t.timeWarp",
"set_pitch":"v.setPitch",
"set_yaw":"v.setYaw",
"set_roll":"v.setRoll",
"set_6dof":"v.setPitchYawRollXYZ",

"gear":"f.gear",
"brake":"f.brake",
"light":"f.light",

"sas":"f.sas",
"sas_on":"f.sas[1]",
"sas_off":"f.sas[0]",
"rcs":"f.rcs",
"rcs_on":"f.rcs[1]",
"rcs_off":"f.rcs[0]",

"enable_fbw":"b.setFbW[1]",
"disable_fbw":"b.setFbW[0]",
"set_fbw":"b.setFbW"
}